import json
import sys

from build_full_dataset_file import ts_header, make_phrase, cat_titles

raw_data = [
    # GREETINGS (1 - 25)
    ("greetings-1", "Greetings", "Merhaba!", "Hallo!", "Hello!", "¡Hola!", "Bonjour !", "Ciao!", "Здравствуйте!", "こんにちは (Konnichiwa)", "你好 (Nǐ hǎo)", "مرحبا (Marhaban)", "안녕하세요 (Annyeonghaseyo)", "Halo", "Helou", "Konniciwa", "Ni hao", "Marhaban", "Annyonghaseyo", "En temel selamlaşma ifadesidir.", "Universal standard greeting phrase."),
    ("greetings-2", "Greetings", "Günaydın!", "Guten Morgen!", "Good morning!", "¡Buenos días!", "Bonjour !", "Buongiorno!", "Доброе утро!", "おはようございます (Ohayō gozaimasu)", "早上好 (Zǎoshang hǎo)", "صباح الخير (Sabah al-khayr)", "좋은 아침입니다 (Joheun achimimnida)", "Guten morgen", "Gud morning", "Ohayo gozaymasu", "Zaosang hao", "Sabah al hayr", "Johun acimimnida", "Sabah saatlerinde söylenen dilek.", "Standard morning greeting."),
    ("greetings-3", "Greetings", "İyi akşamlar!", "Guten Abend!", "Good evening!", "¡Buenas noches!", "Bonsoir !", "Buonasera!", "Добрый вечер!", "こんばんは (Konbanwa)", "晚上好 (Wǎnshang hǎo)", "مساء الخير (Masa' al-khayr)", "좋은 저녁입니다 (Joheun jeonyeogimnida)", "Guten abend", "Gud ivning", "Konbanva", "Vansang hao", "Masa al hayr", "Johun jonyogimnida", "Akşam karşılaşmalarında kullanılan nezaket ifadesi.", "Evening greeting."),
    ("greetings-4", "Greetings", "İyi geceler!", "Gute Nacht!", "Good night!", "¡Buenas noches!", "Bonne nuit !", "Buona notte!", "Спокойной ночи!", "おやすみなさい (Oyasuminasai)", "晚安 (Wǎn'ān)", "تصبح على خير (Tusbih 'ala khayr)", "안녕히 주무세요 (Annyeonghi jumuseyo)", "Gute naht", "Gud nayt", "Oyasuminasai", "Vanan", "Tusbih ala hayr", "Annyonghi jumuseyo", "Gece ayrılırken veya yatmadan önce söylenir.", "Bedtime or late night farewell."),
    ("greetings-5", "Greetings", "Hoşça kal / Güle güle!", "Auf Wiedersehen!", "Goodbye!", "¡Hasta luego!", "Au revoir !", "Arrivederci!", "До свидания!", "さようなら (Sayōnara)", "再见 (Zàijiàn)", "مع السلامة (Ma'a as-salama)", "안녕히 계세요 (Annyeonghi gyeseyo)", "Auf viderzeyen", "Gud bay", "Sayonara", "Caijiyen", "Maas selame", "Annyonghi gyeseyo", "Veda ederken kullanılan resmi ve nazik ifade.", "Formal farewell."),
    ("greetings-6", "Greetings", "Nasılsınız?", "Wie geht es Ihnen?", "How are you?", "¿Cómo está usted?", "Comment allez-vous ?", "Come sta?", "Как ваши дела?", "お元気ですか？ (Ogenki desu ka?)", "你好吗？ (Nǐ hǎo ma?)", "كيف حالك؟ (Kayfa haluk?)", "어떻게 지내세요? (Eotteohke jinaeseyo?)", "Vi get es inen", "Hav ar yu", "Ogenki des ka", "Ni hao ma", "Keyfe haluk", "Ottohke jineseyo", "Karşı tarafın hatırını sorma cümlesi.", "Asking about someone's well-being."),
    ("greetings-7", "Greetings", "İyiyim, teşekkür ederim.", "Mir geht es gut, danke.", "I am fine, thank you.", "Estoy bien, gracias.", "Je vais bien, merci.", "Sto bene, grazie.", "Я в порядке, спасибо.", "元気です、ありがとう (Genki desu, arigatō)", "我很好，谢谢 (Wǒ hěn hǎo, xièxie)", "أنا بخير، شكراً (Ana bikhayr, shukran)", "잘 지내요, 감사합니다 (Jal jinaeyo, gamsahamnida)", "Mir get es gut danke", "Ay em fayn tenk yu", "Genki des arigato", "Vo hen hao xie xie", "Ana bihayr sukran", "Cal jineyo kamsahamnida", "Olumlu durum beyanı.", "Expressing that you are fine."),
    ("greetings-8", "Greetings", "Adınız nedir?", "Wie heißen Sie?", "What is your name?", "¿Cómo se llama?", "Comment vous appelez-vous ?", "Come si chiama?", "Как вас зовут?", "お名前は何ですか？ (Onamae wa nan desu ka?)", "您叫什么名字？ (Nín jiào shénme míngzi?)", "ما اسمك؟ (Ma ismuk?)", "이름이 무엇인가요? (Ireumi mueosingayo?)", "Vi haysen zi", "Vat iz yor neym", "Onamae va nan des ka", "Nin ciao semme minzi", "Ma ismuk", "Ireumi mueosingayo", "İsim sorma sorusu.", "Asking for a person's name."),
    ("greetings-9", "Greetings", "Benim adım...", "Ich heiße...", "My name is...", "Me llamo...", "Je m'appelle...", "Mi chiamo...", "Меня зовут...", "私の名前は...です (Watashi no namae wa... desu)", "我的名字是... (Wǒ de míngzi shì...)", "اسمي... (Ismi...)", "제 이름은 ...입니다 (Je ireumeun... imnida)", "İh hayse", "May neym iz", "Vatasi no namae va", "Vo de minzi si", "İsmi", "Ce iremun imnida", "Kendini tanıtma cümlesi.", "Introducing oneself."),
    ("greetings-10", "Greetings", "Tanıştığımıza memnun oldum.", "Schön, Sie kennenzulernen.", "Nice to meet you.", "Encantado de conocerle.", "Ravi de vous rencontrer.", "Piacere di conoscerla.", "Приятно познакомиться.", "はじめまして (Hajimemashite)", "很高兴认识你 (Hěn gāoxìng rènshi nǐ)", "تشرفت بمعرفتك (Tasharraftu bima'rifatik)", "만나서 반갑습니다 (Mannaseo bangapseumnida)", "Şön zi kenenculernen", "Nays tu mit yu", "Hacimemasite", "Hen gaosin rensi ni", "Tasarraftu bimarifetik", "Mannaso pangapseumnida", "Yeni biriyle tanışma nezaketi.", "Expressing pleasure upon meeting someone."),
    ("greetings-11", "Greetings", "Nerelisiniz?", "Woher kommen Sie?", "Where are you from?", "¿De dónde es usted?", "D'où venez-vous ?", "Di dov'è?", "Откуда вы?", "どちらから来ましたか？ (Dochira kara kimashita ka?)", "您来自哪里？ (Nín láizì nǎlǐ?)", "من أين أنت؟ (Min ayna ant?)", "어디에서 오셨나요? (Eodieseo osyeonnahyo?)", "Voher komen zi", "Ver ar yu derived", "Docira kara kimasita ka", "Nin layzi nali", "Min eyne ent", "Odieseo osyonnahyo", "Memleket sorma sorusu.", "Asking for origin or nationality."),
    ("greetings-12", "Greetings", "Ben ...'dan geliyorum.", "Ich komme aus...", "I come from...", "Vengo de...", "Je viens de...", "Vengo da...", "Я из...", "私は...から来ました (Watashi wa... kara kimashita)", "我来自... (Wǒ láizì...)", "أنا من... (Ana min...)", "저는 ...에서 왔습니다 (Jeoneun... eseo wasseumnida)", "İh kome aus", "Ay kam fram", "Vatasi va kara kimasita", "Vo layzi", "Ana min", "Jeonun eseo vassemnida", "Menşe veya ülke belirtme.", "Stating origin."),
    ("greetings-13", "Greetings", "Kaç yaşındasınız?", "Wie alt sind Sie?", "How old are you?", "¿Cuántos años tiene?", "Quel âge avez-vous ?", "Quanti anni ha?", "Сколько вам лет?", "おいくつですか？ (Oikutsu desu ka?)", "您多大岁数？ (Nín duō dà suìshu?)", "كم عمرك؟ (Kam 'umruk?)", "나이가 어떻게 되시나요? (Naiga eotteohke dwesinayo?)", "Vi alt zint zi", "Hav old ar yu", "Oikutsu des ka", "Nin duo da suysu", "Kem umruk", "Naiga ottohke dwesinayo", "Yaş sorma sorusu.", "Asking about age."),
    ("greetings-14", "Greetings", "Lütfen", "Bitte", "Please", "Por favor", "S'il vous plaît", "Per favore", "Пожалуйста", "お願いします (Onegai shimasu)", "请 (Qǐng)", "من فضلك (Min fadlik)", "부탁합니다 (Butakhamnida)", "Bite", "Pliz", "Onegay simas", "Çing", "Min fadlik", "Putakhamnida", "Rica ve nezaket sözcüğü.", "Word of polite request."),
    ("greetings-15", "Greetings", "Teşekkür ederim", "Danke schön", "Thank you", "Muchas gracias", "Merci beaucoup", "Grazie mille", "Большое спасибо", "ありがとうございます (Arigatō gozaimasu)", "谢谢 (Xièxie)", "شكراً جزيلاً (Shukran jazilan)", "감사합니다 (Gamsahamnida)", "Danke şön", "Tenk yu", "Arigato gozaymasu", "Xie xie", "Sukran cazilan", "Kamsahamnida", "Teşekkür beyanı.", "Expressing gratitude."),
    ("greetings-16", "Greetings", "Rica ederim", "Bitte schön / Gern geschehen", "You are welcome", "De nada", "De rien", "Prego", "Пожалуйста / Не за что", "どういたしまして (Dōitashimashite)", "不客气 (Bù kèqi)", "عفواً (Affwan)", "천만에요 (Cheonmaneyo)", "Gern geşeyen", "Yur velkam", "Doytasimasite", "Bu keçi", "Afvan", "Chonmaneyo", "Teşekküre karşılık verme.", "Response to thank you."),
    ("greetings-17", "Greetings", "Evet", "Ja", "Yes", "Sí", "Oui", "Sì", "Да", "はい (Hai)", "是 (Shì)", "نعم (Na'am)", "네 (Ne)", "Ya", "Yes", "Hay", "Si", "Naam", "Ne", "Onay bildirme.", "Affirmation."),
    ("greetings-18", "Greetings", "Hayır", "Nein", "No", "No", "Non", "No", "Нет", "いいえ (Iie)", "不 (Bù)", "لا (La)", "아니요 (Aniyo)", "Nayn", "No", "Iye", "Bu", "La", "Aniyo", "Reddetme veya olumsuzluk.", "Negation."),
    ("greetings-19", "Greetings", "Affedersiniz / Özür dilerim", "Entschuldigung", "Excuse me / Sorry", "Disculpe / Lo siento", "Pardon / Désolé", "Scusi / Mi dispiace", "Извините / Простите", "すみません (Sumimasen)", "抱歉 / 对不起 (Bàoqiàn / Duìbuqǐ)", "معذرة / آسف (Ma'dhiratan / Asif)", "죄송합니다 (Joesonghamnida)", "Entşuldigung", "Ekskyuz mi", "Sumimasen", "Duybuçi", "Maziraten", "Joesonghamnida", "Nezaket ve özür ifadesi.", "Polite apology or getting attention."),
    ("greetings-20", "Greetings", "Anlamıyorum", "Ich verstehe nicht", "I do not understand", "No entiendo", "Je ne comprends pas", "Non capisco", "Я не понимаю", "わかりません (Wakarimasen)", "我不明白 (Wǒ bù míngbai)", "لا أفهم (La afham)", "이해가 안 돼요 (Ihaega an dwaeyo)", "İh ferştehe niht", "Ay do not understand", "Vakarimasen", "Vo bu mingbai", "La afham", "Ihega an dveyo", "Anlaşılmadığını belirtme.", "Expressing non-comprehension."),
    ("greetings-21", "Greetings", "İngilizce biliyor musunuz?", "Sprechen Sie Englisch?", "Do you speak English?", "¿Habla inglés?", "Parlez-vous anglais ?", "Parla inglese?", "Вы говорите по-английски?", "英語を話せますか？ (Eigo wo hanasemasu ka?)", "你会说英语吗？ (Nǐ huì shuō Yīngyǔ ma?)", "هل تتكلم الإنجليزية؟ (Hal tatakallam al-ingliziyya?)", "영어 할 수 있어요? (Yeong-eo hal su isseoyo?)", "Şprehen zi engliş", "Du yu spik engliş", "Eygo vo hanasemas ka", "Ni huy suo yingyu ma", "Hel tatakallam ingilizce", "Yong-o hal su isseoyo", "Dil yeterliliği sorma.", "Asking if someone speaks English."),
    ("greetings-22", "Greetings", "Biraz...", "Ein wenig...", "A little...", "Un poco...", "Un peu...", "Un po'...", "Немного...", "少し... (Sukoshi...)", "一点点... (Yì diǎndiǎn...)", "قليلاً... (Qalilan...)", "조금... (Jogeum...)", "Ayn venig", "E litıl", "Sukosi", "Yi diandian", "Kalilan", "Jogum", "Miktar belirtme.", "Expressing a small amount."),
    ("greetings-23", "Greetings", "Sonra görüşürüz!", "Bis später!", "See you later!", "¡Hasta luego!", "À plus tard !", "A dopo!", "До встречи!", "また後で (Mata ato de)", "回头见 (Huítóu jiàn)", "أراك لاحقاً (Araka lahiqan)", "나중에 봐요 (Najunge bwayo)", "Bis şpeter", "Si yu leyter", "Mata ato de", "Huytou ciyan", "Araka lahikan", "Najunge bwayo", "Kısa süreli ayrılık veda sözü.", "Farewell for returning later."),
    ("greetings-24", "Greetings", "İyi şanslar!", "Viel Glück!", "Good luck!", "¡Buena suerte!", "Bonne chance !", "Buona fortuna!", "Удачи!", "幸運を祈ります (Kōun wo inorimasu)", "祝你好运 (Zhù nǐ hǎo yùn)", "حظاً سعيداً (Hazzan sa'idan)", "행운을 빌어요 (Haenguneul bireoyo)", "Fil glük", "Gud lak", "Koun vo inorimas", "Ju ni hao yun", "Hazzan saidan", "Hengunul biroyo", "Dilek cümlesi.", "Wishing good luck."),
    ("greetings-25", "Greetings", "Tebrikler!", "Herzlichen Glückwunsch!", "Congratulations!", "¡Felicidades!", "Félicitations !", "Congratulazioni!", "Поздравляю!", "おめでとうございます (Omedetō gozaimasu)", "恭喜！ (Gōngxǐ!)", "مبروك! (Mabruk!)", "축하합니다! (Chukhahamnida!)", "Hertslihen glükvunş", "Kangraculeyşıns", "Omedeto gozaymas", "Gongsi", "Mabruk", "Cukhahamnida", "Kutlama ifadesi.", "Expressing congratulations.")
]

print(f"Base greetings count: {len(raw_data)}")
